name: docker-build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - distro: debian
            distro_version: bookworm-slim
            tags: bookworm-slim,latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          registry: docker.pkg.github.com
          platforms: linux/${{ matrix.arch }}
          build-args: -|
            DISTRO_VERSION=${{ matrix.distro_version }}
          dockerfile: ./image/${{ matrix.distro }}/Dockerfile
          context: .
          repository: 74th/github-actions-self-hosted-runner-container/${{ matrix.distro }}
          tags: ${{ matrix.distro_version }}