name: docker-build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        distro:
          - debian
        include:
          - distro: debian
            distro_version: buster-slim
            tags: buster-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./image/${{ matrix.distro }}/Dockerfile
          platforms: linux/${{ matrix.arch }}
          build-args: |
            DISTRO_VERSION=${{ matrix.distro_version }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
          labels: ${{ matrix.distro_version }}
          push: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true